DROP TABLE soc_net_follower;
DROP TABLE soc_net_user;

CREATE TABLE soc_net_user (
    user_id     INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50) NOT NULL,
    email       VARCHAR(30) UNIQUE NOT NULL,
    password    VARCHAR(20) NOT NULL,
    address     VARCHAR(50) NOT NULL,
    phone       VARCHAR(13),       
    PRIMARY KEY(user_id)
);

CREATE TABLE soc_net_follower (
    user_id NUMBER,
    follower_id NUMBER,
    CONSTRAINT is_user FOREIGN KEY (user_id) REFERENCES soc_net_user(user_id) ON DELETE CASCADE,
    CONSTRAINT following_by FOREIGN KEY (follower_id) REFERENCES soc_net_user(user_id) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER max_followers
BEFORE INSERT ON soc_net_follower
FOR EACH ROW
DECLARE
	result int;
BEGIN
    SELECT COUNT(*) INTO result FROM soc_net_follower
    JOIN soc_net_user u ON (soc_net_follower.user_id = u.user_id)
    JOIN soc_net_user f ON (soc_net_follower.follower_id = f.user_id)
    WHERE u.user_id = :new.user_id;

	IF result >= 5 THEN
		raise_application_error(-20001, 'Max limit of followers!');
	END IF;
END;
/

-- INSERT USERS
INSERT INTO soc_net_user(user_id, first_name, last_name, email, password, address, phone) VALUES (NULL, 'Patrik', 'Trstensky', 'patrik@gmail.com', 'patrikpswd' , 'Patrik address','+421111111111');
INSERT INTO soc_net_user(user_id, first_name, last_name, email, password, address, phone) VALUES (NULL, 'Domink', 'Lonek', 'domink@gmail.com', 'dominkpswd' , 'Domink address','+421111111111');
INSERT INTO soc_net_user(user_id, first_name, last_name, email, password, address, phone) VALUES (NULL, 'Martin', 'Novak', 'martin@gmail.com', 'martinpswd' , 'Martin address','+421111111111');
INSERT INTO soc_net_user(user_id, first_name, last_name, email, password, address, phone) VALUES (NULL, 'Jozef', 'Velicny', 'jozef@gmail.com', 'jozefpswd' , 'Jozef address','+421111111111');

-- INSERT FOLLOWERS
INSERT INTO soc_net_follower(user_id,follower_id) VALUES (1,2);
INSERT INTO soc_net_follower(user_id,follower_id) VALUES (1,3);
INSERT INTO soc_net_follower(user_id,follower_id) VALUES (1,4);

INSERT INTO soc_net_follower(user_id,follower_id) VALUES (4,2);
INSERT INTO soc_net_follower(user_id,follower_id) VALUES (4,1);